use crate::error::{Error, Result};

/// Decode a JPEG byte stream into raw pixels.
///
/// Returns a `DecodedJpeg` with raw pixel bytes (1 byte/pixel for gray,
/// 3 bytes/pixel for RGB), dimensions, and the detected color space.
pub fn decode(data: &[u8]) -> Result<DecodedJpeg> {
    let mut decoder = jpeg_decoder::Decoder::new(data);
    let pixels = decoder
        .decode()
        .map_err(|e| Error::InvalidPdf(format!("JPEG decode error: {e}")))?;
    let info = decoder
        .info()
        .ok_or_else(|| Error::InvalidPdf("JPEG: no info after decode".into()))?;

    let color_space = match info.pixel_format {
        jpeg_decoder::PixelFormat::L8 | jpeg_decoder::PixelFormat::L16 => JpegColorSpace::Grayscale,
        jpeg_decoder::PixelFormat::RGB24 => JpegColorSpace::Rgb,
        jpeg_decoder::PixelFormat::CMYK32 => JpegColorSpace::Cmyk,
    };

    Ok(DecodedJpeg {
        pixels,
        width: info.width as u32,
        height: info.height as u32,
        color_space,
    })
}

/// Result of a JPEG decode operation.
pub struct DecodedJpeg {
    /// Raw pixel data (gray: 1 byte/pixel, RGB: 3 bytes/pixel, CMYK: 4 bytes/pixel).
    pub pixels: Vec<u8>,
    pub width: u32,
    pub height: u32,
    pub color_space: JpegColorSpace,
}

/// Color space reported by the JPEG decoder.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JpegColorSpace {
    Grayscale,
    Rgb,
    Cmyk,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal valid 1×1 white grayscale JPEG generated by ImageMagick.
    const GRAY_1X1_JPEG: &[u8] = include_bytes!("../../tests/fixtures/gray_1x1.jpg");

    #[test]
    fn decode_gray_1x1_jpeg() {
        let result = decode(GRAY_1X1_JPEG).unwrap();
        assert_eq!(result.width, 1);
        assert_eq!(result.height, 1);
        assert_eq!(result.color_space, JpegColorSpace::Grayscale);
        assert_eq!(result.pixels.len(), 1);
        // White pixel: value near 255 (may differ slightly due to DCT rounding)
        assert!(
            result.pixels[0] > 200,
            "expected white pixel, got {}",
            result.pixels[0]
        );
    }

    #[test]
    fn decode_invalid_data_is_error() {
        let result = decode(b"not a jpeg");
        assert!(result.is_err());
    }
}
